[build]
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "client/build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[context.branch-deploy.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[context.next.environment]
  NPM_FLAGS = "--legacy-peer-deps"
